server:
  port: 8080

spring:
  application:
    name: kotlin
  profiles:
    include:
      - redis
      - datasource
      - mqtt
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

jasypt:
  encryptor:
    # 加密时的盐值
    password: ${spring.application.name}

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    io.intellij.examples.kotlin.mapper: debug