server:
  port: 8080

spring:
  application:
    name: kotlin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.100.1.100:3306/kotlin?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 172.100.1.100
      port: 6379
      password: root
      database: 15
      lettuce:
        pool:
          max-active: 8
          # 连接分配应该阻塞的最大时间
          max-wait: 5000
          max-idle: 8
          min-idle: 0

  # mqtt config
  mqtt:
    publish:
      broker: tcp://172.100.1.100:1883
      username: username
      password: password
      clientId: kotlin-example-publish
      defaultTopic: /topic/default
    subscribe:
      broker: tcp://172.100.1.100:1883
      username: username
      password: password
      clientId: kotlin-example-subscribe
      topics:
        - /topic/default
        - /hello/world

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

jasypt:
  encryptor:
    # 加密时的盐值
    password: ${spring.application.name}

logging:
  level:
    # mapper 日志输出
    io.intellij.examples.kotlin.mapper: debug